name: Smart Contract CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests (NO FORK)
        run: forge test -vv --no-match-path "test/Fork.t.sol|test/UniswapFork.t.sol"